// GENERATED by port/tools/gen_game_data.py from include/elf/game.h and the
// layout of the original exe's .data section. Do not edit; `make -C port game-data`.
// Every g_XXXXXX the game declares. Their initial values are NOT here: elf_game_data_load
// copies them from the user's exe at startup (file offsets only; no bytes of the exe).
#include <vcl/vcl.h>
#include <elf/funcs.h>
#include <string.h>

#define ELF_STR2(x) #x
#define ELF_STR(x) ELF_STR2(x)
#define ELF_ASM(n) __asm__(ELF_STR(__USER_LABEL_PREFIX__) #n)

extern "C" {

TStage *g_4601c8;   // 0x4601c8, 4 bytes (32-bit)
TStage *g_456c38;   // 0x456c38, 4 bytes (32-bit)
TSoundMgr *g_460208;   // 0x460208, 4 bytes (32-bit)
TPackedResources *g_455524;   // 0x455524, 4 bytes (32-bit)
TSaveParms *g_455528;   // 0x455528, 4 bytes (32-bit)
TPackedResources *g_460218;   // 0x460218, 4 bytes (32-bit)
TWebTrack *g_46020c;   // 0x46020c, 4 bytes (32-bit)
void *g_4601c0;   // 0x4601c0, 4 bytes (32-bit)
void *g_460214;   // 0x460214, 4 bytes (32-bit)
BITMAPINFOHEADER *g_45552c;   // 0x45552c, 4 bytes (32-bit)
unsigned char g_455530;   // 0x455530, 1 bytes (32-bit)
unsigned char g_455531;   // 0x455531, 1 bytes (32-bit)
int g_455534;   // 0x455534, 4 bytes (32-bit)
int g_455538;   // 0x455538, 4 bytes (32-bit)
char g_45553c;   // 0x45553c, 1 bytes (32-bit)
int g_455540;   // 0x455540, 4 bytes (32-bit)
int g_455544;   // 0x455544, 4 bytes (32-bit)
bool g_455548;   // 0x455548, 1 bytes (32-bit)
int g_4555ac;   // 0x4555ac, 4 bytes (32-bit)
int g_4555bc;   // 0x4555bc, 4 bytes (32-bit)
int g_4555c0;   // 0x4555c0, 4 bytes (32-bit)
HGDIOBJ g_4601cc[8];   // 0x4601cc, 32 bytes (32-bit), first bound 8 from the gap
char g_4601ec;   // 0x4601ec, 1 bytes (32-bit)
HGDIOBJ g_4601f0;   // 0x4601f0, 4 bytes (32-bit)
HDC g_4601f4;   // 0x4601f4, 4 bytes (32-bit)
HDC g_4601f8;   // 0x4601f8, 4 bytes (32-bit)
HPALETTE g_4601fc;   // 0x4601fc, 4 bytes (32-bit)
int g_460200;   // 0x460200, 4 bytes (32-bit)
int g_460204;   // 0x460204, 4 bytes (32-bit)
int g_45554c;   // 0x45554c, 4 bytes (32-bit)
unsigned g_455550;   // 0x455550, 4 bytes (32-bit)
int g_455554;   // 0x455554, 4 bytes (32-bit)
unsigned g_455558;   // 0x455558, 4 bytes (32-bit)
unsigned g_45555c;   // 0x45555c, 4 bytes (32-bit)
unsigned g_455560;   // 0x455560, 4 bytes (32-bit)
unsigned g_455564;   // 0x455564, 4 bytes (32-bit)
unsigned g_455568;   // 0x455568, 4 bytes (32-bit)
char *g_460228;   // 0x460228, 4 bytes (32-bit)
int g_46022c;   // 0x46022c, 4 bytes (32-bit)
int g_460230;   // 0x460230, 4 bytes (32-bit)
bool g_460234;   // 0x460234, 1 bytes (32-bit)
int g_460238;   // 0x460238, 4 bytes (32-bit)
const char *g_456ee8[12] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456ee8, 48 bytes (32-bit), first bound 12 from the gap
const char *g_456f18[9] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456f18, 36 bytes (32-bit), first bound 9 from the gap
const char *g_456f3c[8] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456f3c, 32 bytes (32-bit), first bound 8 from the gap
const char *g_456f5c[7] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456f5c, 28 bytes (32-bit), first bound 7 from the gap
const char *g_456f78[9] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456f78, 36 bytes (32-bit), first bound 9 from the gap
const char *g_456f9c[7] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x456f9c, 28 bytes (32-bit), first bound 7 from the gap
int g_456fb8_rw[10] ELF_ASM(g_456fb8);   // 0x456fb8, 40 bytes (32-bit)
int g_456fe0_rw[10] ELF_ASM(g_456fe0);   // 0x456fe0, 40 bytes (32-bit)
TSpriteGroup *g_46023c;   // 0x46023c, 4 bytes (32-bit)
TSpriteGroup *g_460538;   // 0x460538, 4 bytes (32-bit)
TSpriteGroup *g_46053c;   // 0x46053c, 4 bytes (32-bit)
TSpriteGroup *g_460540;   // 0x460540, 4 bytes (32-bit)
TSpriteGroup *g_460544;   // 0x460544, 4 bytes (32-bit)
TSpriteGroup *g_460548;   // 0x460548, 4 bytes (32-bit)
TSpriteGroup *g_46054c;   // 0x46054c, 4 bytes (32-bit)
TSpriteGroup *g_460550;   // 0x460550, 4 bytes (32-bit)
TSpriteGroup *g_460554;   // 0x460554, 4 bytes (32-bit)
TSpriteGroup *g_460558;   // 0x460558, 4 bytes (32-bit)
TSpriteGroup *g_46055c;   // 0x46055c, 4 bytes (32-bit)
TSpriteGroup *g_460560;   // 0x460560, 4 bytes (32-bit)
TSpriteGroup *g_460564;   // 0x460564, 4 bytes (32-bit)
TSpriteGroup *g_460568;   // 0x460568, 4 bytes (32-bit)
TSpriteGroup *g_46056c;   // 0x46056c, 4 bytes (32-bit)
TSpriteGroup *g_460570;   // 0x460570, 4 bytes (32-bit)
TSpriteGroup *g_460574;   // 0x460574, 4 bytes (32-bit)
TSpriteGroup *g_460750;   // 0x460750, 4 bytes (32-bit)
TSpriteGroup *g_460778;   // 0x460778, 4 bytes (32-bit)
TSpriteGroup *g_46077c;   // 0x46077c, 4 bytes (32-bit)
PinState g_460240[10];   // 0x460240, 80 bytes (32-bit)
bool g_460578[10];   // 0x460578, 10 bytes (32-bit)
bool g_460582[10];   // 0x460582, 10 bytes (32-bit)
bool g_46058c[10];   // 0x46058c, 10 bytes (32-bit)
bool g_460596;   // 0x460596, 1 bytes (32-bit)
bool g_460597;   // 0x460597, 1 bytes (32-bit)
int g_460598;   // 0x460598, 4 bytes (32-bit)
int g_46059c;   // 0x46059c, 4 bytes (32-bit)
bool g_4605a0;   // 0x4605a0, 1 bytes (32-bit)
bool g_4605a1;   // 0x4605a1, 1 bytes (32-bit)
bool g_4605a2;   // 0x4605a2, 1 bytes (32-bit)
bool g_4605a3;   // 0x4605a3, 1 bytes (32-bit)
bool g_4605a4;   // 0x4605a4, 1 bytes (32-bit)
int g_4605a8;   // 0x4605a8, 4 bytes (32-bit)
int g_4605ac;   // 0x4605ac, 4 bytes (32-bit)
int *g_4605b0;   // 0x4605b0, 4 bytes (32-bit)
bool g_4605b4;   // 0x4605b4, 1 bytes (32-bit)
int *g_4605b8;   // 0x4605b8, 4 bytes (32-bit)
int g_4605bc;   // 0x4605bc, 4 bytes (32-bit)
int g_4605c0;   // 0x4605c0, 4 bytes (32-bit)
int g_4605c4;   // 0x4605c4, 4 bytes (32-bit)
FrameScore g_4605c8[12];   // 0x4605c8, 192 bytes (32-bit)
int g_460688;   // 0x460688, 4 bytes (32-bit)
int g_46068c;   // 0x46068c, 4 bytes (32-bit)
bool g_460690;   // 0x460690, 1 bytes (32-bit)
int g_460694;   // 0x460694, 4 bytes (32-bit)
bool g_460698[2];   // 0x460698, 2 bytes (32-bit)
int g_46069c;   // 0x46069c, 4 bytes (32-bit)
int g_4606a0;   // 0x4606a0, 4 bytes (32-bit)
int g_4606a4;   // 0x4606a4, 4 bytes (32-bit)
bool g_4606a8[2];   // 0x4606a8, 2 bytes (32-bit)
int g_4606ac;   // 0x4606ac, 4 bytes (32-bit)
bool g_4606b0;   // 0x4606b0, 1 bytes (32-bit)
bool g_4606b1;   // 0x4606b1, 1 bytes (32-bit)
int g_4606c8;   // 0x4606c8, 4 bytes (32-bit)
int g_4606cc;   // 0x4606cc, 4 bytes (32-bit)
int g_4606d0;   // 0x4606d0, 4 bytes (32-bit)
int g_4606d4;   // 0x4606d4, 4 bytes (32-bit)
int g_4606d8;   // 0x4606d8, 4 bytes (32-bit)
int g_4606dc;   // 0x4606dc, 4 bytes (32-bit)
int g_4606e0;   // 0x4606e0, 4 bytes (32-bit)
int g_4606e4;   // 0x4606e4, 4 bytes (32-bit)
int g_4606e8;   // 0x4606e8, 4 bytes (32-bit)
char g_4606ec;   // 0x4606ec, 1 bytes (32-bit)
int g_4606f0;   // 0x4606f0, 4 bytes (32-bit)
int g_4606f4;   // 0x4606f4, 4 bytes (32-bit)
char g_4606f8[10];   // 0x4606f8, 10 bytes (32-bit)
int g_460704[12];   // 0x460704, 48 bytes (32-bit)
int g_460734;   // 0x460734, 4 bytes (32-bit)
char g_460738;   // 0x460738, 1 bytes (32-bit)
int g_46073c;   // 0x46073c, 4 bytes (32-bit)
int g_460740;   // 0x460740, 4 bytes (32-bit)
char g_460744;   // 0x460744, 1 bytes (32-bit)
int g_460748;   // 0x460748, 4 bytes (32-bit)
int g_46074c;   // 0x46074c, 4 bytes (32-bit)
int g_460754;   // 0x460754, 4 bytes (32-bit)
bool g_460758;   // 0x460758, 1 bytes (32-bit)
bool g_460759;   // 0x460759, 1 bytes (32-bit)
int g_46075c[4];   // 0x46075c, 16 bytes (32-bit)
int g_46076c;   // 0x46076c, 4 bytes (32-bit)
int g_460770;   // 0x460770, 4 bytes (32-bit)
char *g_460780;   // 0x460780, 4 bytes (32-bit)
int g_460784;   // 0x460784, 4 bytes (32-bit)
int g_460788;   // 0x460788, 4 bytes (32-bit)
int g_46078c;   // 0x46078c, 4 bytes (32-bit)
int g_458840[10];   // 0x458840, 40 bytes (32-bit), first bound 10 from the gap
int g_458868;   // 0x458868, 4 bytes (32-bit)
char g_45886c;   // 0x45886c, 1 bytes (32-bit)
bool g_45886d;   // 0x45886d, 1 bytes (32-bit)
int g_458870;   // 0x458870, 4 bytes (32-bit)
const char *g_458874[2] = {
    nullptr,
    nullptr,
};   // 0x458874, 8 bytes (32-bit), first bound 2 from the gap
const char *g_45887c[2] = {
    nullptr,
    nullptr,
};   // 0x45887c, 8 bytes (32-bit), first bound 2 from the gap
int g_458884[6][3][10];   // 0x458884, 720 bytes (32-bit), first bound 6 from the gap
int g_458b54[6][3][10];   // 0x458b54, 720 bytes (32-bit), first bound 6 from the gap
int g_458e24[6][3][10];   // 0x458e24, 720 bytes (32-bit), first bound 6 from the gap
int g_4590f4[12];   // 0x4590f4, 48 bytes (32-bit), first bound 12 from the gap
int g_459124;   // 0x459124, 4 bytes (32-bit)
const char *g_45aaf4[29] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x45aaf4, 116 bytes (32-bit), first bound 29 from the gap
const char *g_45ab68[26] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};   // 0x45ab68, 104 bytes (32-bit), first bound 26 from the gap
void (*g_45c41c)(const char *msg);   // 0x45c41c, 4 bytes (32-bit)
unsigned g_cplens_45c0f0[31];   // 0x45c0f0, 124 bytes (32-bit), declared in zlib_41e2cc.cpp
unsigned g_cplext_45c16c[31];   // 0x45c16c, 124 bytes (32-bit), declared in zlib_41e2cc.cpp
unsigned g_cpdist_45c1e8[30];   // 0x45c1e8, 120 bytes (32-bit), declared in zlib_41e2cc.cpp
unsigned g_cpdext_45c260[30];   // 0x45c260, 120 bytes (32-bit), declared in zlib_41e2cc.cpp
int g_fixed_built_45c2d8;   // 0x45c2d8, 4 bytes (32-bit), declared in zlib_41e2cc.cpp
unsigned g_inflate_mask_45c3ac[17];   // 0x45c3ac, 68 bytes (32-bit), declared in zlib_41e2cc.cpp
unsigned g_border_45bf2c[113];   // 0x45bf2c, 452 bytes (32-bit), declared in zlib_41e2cc.cpp, first bound 113 from the gap

}   // extern "C"

// kind: i/I signed/unsigned integers, B bool, R raw bytes, S pointer to the string at off
struct ElfDataRec { void *dst; unsigned off, count, size32, nsize; char kind; };
static const ElfDataRec k_elf_data[] = {
    {(void *)&g_455531, 0x54331, 1, 1, (unsigned)(sizeof(g_455531) / 1), 'I'},
    {(void *)&g_455554, 0x54354, 1, 4, (unsigned)(sizeof(g_455554) / 1), 'i'},
    {(void *)&g_456ee8[0], 0x55e08, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[1], 0x55e46, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[2], 0x55e48, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[3], 0x55ea5, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[4], 0x55f02, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[5], 0x55f61, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[6], 0x55fbe, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[7], 0x56018, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[8], 0x5603a, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[9], 0x5603c, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[10], 0x56087, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456ee8[11], 0x56089, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[0], 0x560d2, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[1], 0x56115, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[2], 0x5616d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[3], 0x561cb, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[4], 0x561cd, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[5], 0x5620c, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[6], 0x5626d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[7], 0x562cd, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f18[8], 0x5632a, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[0], 0x5638a, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[1], 0x563d6, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[2], 0x56430, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[3], 0x56480, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[4], 0x564da, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[5], 0x564dc, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[6], 0x5651e, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f3c[7], 0x56574, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[0], 0x565ce, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[1], 0x56605, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[2], 0x56660, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[3], 0x566b2, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[4], 0x566b4, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[5], 0x566ed, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f5c[6], 0x5671d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[0], 0x56744, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[1], 0x56789, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[2], 0x567d4, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[3], 0x56820, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[4], 0x5685e, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[5], 0x56860, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[6], 0x56895, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[7], 0x568f0, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f78[8], 0x56949, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[0], 0x56984, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[1], 0x569b8, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[2], 0x56a0f, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[3], 0x56a6d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[4], 0x56ac9, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[5], 0x56acb, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456f9c[6], 0x56b00, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_456fb8_rw, 0x55db8, 10, 4, (unsigned)(sizeof(g_456fb8_rw) / 10), 'i'},
    {(void *)&g_456fe0_rw, 0x55de0, 10, 4, (unsigned)(sizeof(g_456fe0_rw) / 10), 'i'},
    {(void *)&g_458840, 0x57640, 10, 4, (unsigned)(sizeof(g_458840) / 10), 'i'},
    {(void *)&g_458874[0], 0x57f69, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_458874[1], 0x57f75, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45887c[0], 0x57f90, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45887c[1], 0x57f9c, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_458884, 0x57684, 180, 4, (unsigned)(sizeof(g_458884) / 180), 'i'},
    {(void *)&g_458b54, 0x57954, 180, 4, (unsigned)(sizeof(g_458b54) / 180), 'i'},
    {(void *)&g_458e24, 0x57c24, 180, 4, (unsigned)(sizeof(g_458e24) / 180), 'i'},
    {(void *)&g_4590f4, 0x57ef4, 12, 4, (unsigned)(sizeof(g_4590f4) / 12), 'i'},
    {(void *)&g_45aaf4[0], 0x599eb, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[1], 0x59a07, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[2], 0x59a09, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[3], 0x59a2b, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[4], 0x59a42, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[5], 0x59a63, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[6], 0x59a7d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[7], 0x59a7f, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[8], 0x59a95, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[9], 0x59ab1, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[10], 0x59acf, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[11], 0x59aeb, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[12], 0x59aed, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[13], 0x59b08, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[14], 0x59b27, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[15], 0x59b41, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[16], 0x59b5e, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[17], 0x59b60, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[18], 0x59b7f, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[19], 0x59ba3, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[20], 0x59bc1, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[21], 0x59be0, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[22], 0x59be2, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[23], 0x59c00, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[24], 0x59c19, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[25], 0x59c32, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[26], 0x59c4f, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[27], 0x59c51, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45aaf4[28], 0x59c62, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[0], 0x59c7f, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[1], 0x59c9e, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[2], 0x59ca0, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[3], 0x59ccf, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[4], 0x59d00, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[5], 0x59d2e, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[6], 0x59d5a, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[7], 0x59d5c, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[8], 0x59d86, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[9], 0x59db7, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[10], 0x59ddd, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[11], 0x59ddf, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[12], 0x59e0c, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[13], 0x59e3b, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[14], 0x59e61, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[15], 0x59e63, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[16], 0x59e92, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[17], 0x59ec3, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[18], 0x59ef0, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[19], 0x59f21, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[20], 0x59f50, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[21], 0x59f7d, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[22], 0x59fac, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[23], 0x59fd5, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[24], 0x59fd7, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_45ab68[25], 0x59ff7, 1, 0, (unsigned)(sizeof(void *)), 'S'},
    {(void *)&g_cplens_45c0f0, 0x5aef0, 31, 4, (unsigned)(sizeof(g_cplens_45c0f0) / 31), 'I'},
    {(void *)&g_cplext_45c16c, 0x5af6c, 31, 4, (unsigned)(sizeof(g_cplext_45c16c) / 31), 'I'},
    {(void *)&g_cpdist_45c1e8, 0x5afe8, 30, 4, (unsigned)(sizeof(g_cpdist_45c1e8) / 30), 'I'},
    {(void *)&g_cpdext_45c260, 0x5b060, 30, 4, (unsigned)(sizeof(g_cpdext_45c260) / 30), 'I'},
    {(void *)&g_inflate_mask_45c3ac, 0x5b1ac, 17, 4, (unsigned)(sizeof(g_inflate_mask_45c3ac) / 17), 'I'},
    {(void *)&g_border_45bf2c, 0x5ad2c, 113, 4, (unsigned)(sizeof(g_border_45bf2c) / 113), 'I'},
};

#define ELF_EXE_SIZE 1130496u   // the exe this table was made from
extern "C" int elf_game_data_load(const unsigned char *img, size_t size)
{
    if (!img || size != ELF_EXE_SIZE)
        return -1;
    for (const ElfDataRec &r : k_elf_data) {
        if (r.kind == 'S') {
            const void *p = img + r.off;
            memcpy(r.dst, &p, sizeof p);
            continue;
        }
        if (r.kind == 'R') {
            memcpy(r.dst, img + r.off, r.size32);
            continue;
        }
        for (unsigned i = 0; i < r.count; i++) {
            const unsigned char *s = img + r.off + i * r.size32;
            unsigned long long v = 0;
            for (unsigned k = 0; k < r.size32; k++)
                v |= (unsigned long long)s[k] << (8 * k);
            if (r.kind == 'i' && r.size32 < 8 && (v >> (8 * r.size32 - 1)) & 1)
                v |= ~0ull << (8 * r.size32);    // sign-extend
            if (r.kind == 'B')
                v = v != 0;
            unsigned char *d = (unsigned char *)r.dst + i * r.nsize;
            for (unsigned k = 0; k < r.nsize; k++)   // little-endian targets only
                d[k] = (unsigned char)(v >> (8 * k));
        }
    }
    return 0;
}

// notes:
//   g_fixed_mem_460798 (inflate_huft, zlib_41e2cc.cpp): no address or not a plain type; the unit must define it natively
//   g_fixed_bl (uInt, zlib_41e2cc.cpp): no address or not a plain type; the unit must define it natively
//   g_fixed_bd (uInt, zlib_41e2cc.cpp): no address or not a plain type; the unit must define it natively
//   g_fixed_tl (inflate_huft, zlib_41e2cc.cpp): no address or not a plain type; the unit must define it natively
//   g_fixed_td (inflate_huft, zlib_41e2cc.cpp): no address or not a plain type; the unit must define it natively
